[project]
name = "xenostream"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.115.8",
    "gunicorn==23.0.0",
    "networkx==2.8.8",
    "numpy==1.26.4",
    "pydantic-settings==2.8.1",
    "python-multipart==0.0.9",
    "soundfile==0.13.1",
    "tokenizers==0.19.1",
    "torch==2.5.1",
    "torchaudio==2.5.1",
    "transformers>=4.33.0,<5",
    "tts==0.22.0",
    "uvicorn[standard]==0.34.0",
]
